### ISSUE TITLE
Export the `KnownBrowsers` & `KnownPlatforms` in the `types` declartion

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [sibiraj-s/browser-dtector#11]
When I wanted to create a helper that would say whether I use Safari I found myself using inconvenient regexes like this:
```
isSafari = /safari/i.test(String(userAgent.name));
```
Instead of:
```
isSafari ==== browser.name === KnownBrowsers.safari
```
That's all because the `KnownBrowsers` is not exported due to the `types` definition: https://github.com/sibiraj-s/browser-dtector/blob/1f60bd44a6c13784790725a66f8a854923acbb05/lib/types.d.ts#L1

**Comment by sibiraj-s** [comment]
Should be available in v4. Merged the PR, also exported actual constants along with types. If you use esm, you should see no difference.

For cjs its is converted into named exports as both constants and BroswerDetector is exported.

Thanks
