### ISSUE TITLE
`TS4023: Exported variable ...  has or is using name  BrowserInfoFull  from external module` error in V4

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [sibiraj-s/browser-dtector#13]
When the TS file in my project has the next structure:
```ts
import BrowserDetector, { KnownBrowsers } from 'browser-dtector';

const browser = new BrowserDetector(window.navigator.userAgent);
export const parsedUserAgent = browser.parseUserAgent();
```
I'm getting an error on the exported `parsedUserAgent` variable:
```
TS4023: Exported variable  parsedUserAgent  has or is using name  BrowserInfoFull  from an external module ".../node_modules/browser-dtector/dist/browser-dtector" but cannot be named
```
The suggested fix is to export the `BrowserInfoFull` from the `browser-dtector` package to let the TS figure out an appropriate name for this type

Demo:
<img width="941" alt="image" src="https://github.com/sibiraj-s/browser-dtector/assets/68850090/992308df-e994-466e-9ce0-28fc8653f774">

**Comment by sibiraj-s** [comment]
Should be fixed in v4.1.0. After typescript migration, the code was still referring to the old types exported types in earlier version.

These are removed now and should work fine. Feel free to reopen if the issue still exists
