### ISSUE TITLE
iPad (Firefox, Opera) and iPhone(Opera) Detected Browser is Wrong

### ISSUE THREAD

**Issue by muharremaras** [sibiraj-s/browser-dtector#7]
Hi,

I tested this library in several devices. I noticed wrong detection in iPad and iPhone.

The library detects In iPad, in Firefox and Opera Browsers
The library detects in iPhone in Opera Browser 

**as "Safari Browser"**

**Comment by sibiraj-s** [comment]
Hi, this could not be a bug, the browsers in ios and ipad os are just webkit underneath unlike android or desktop browsers. Hence its like that. 

I don't have any devices to test this, but i have tested the user agents from https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox. You can test them here https://sibiraj-s.github.io/browser-dtector/#/ua-parser

If you feel this is a bug. Please provide more info. 

Closing the issue till then. Please reopen if required.

**Comment by muharremaras** [comment]
Hi,

I tested what you suggested above in Ipad and Iphone devices using this link: https://sibiraj-s.github.io/browser-dtector. 

Results are (only the wrong ones):

On Iphone: In Opera browser, it detects as Safari. 
On Ipad: In Opera and Firefox, it detects as Safari.

I have conditions for Safari only, so it's important for me to know exactly which browser I'm using. So, even if they're webkit based, I have to know if I'm using Opera or Safari. Is it possible for you to fix this? Thanks.

**Comment by sibiraj-s** [comment]
May be can you share the user agents from your devices?

**Comment by muharremaras** [comment]
for ipad->

opera:
Mozilla/5.0 (iPad; CPU OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1 OPT/4.0.1

firefox:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

safari:
Mozilla/5.0 (iPad; CPU OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1

chrome:
Mozilla/5.0 (iPad; CPU OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1

For Iphone->
Opera:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1 OPT/4.0.1
Chrome:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/114.0.5735.124 Mobile/15E148 Safari/604.1
Firefox:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/114.4 Mobile/15E148 Safari/605.1.15
Safari:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Mobile/15E148 Safari/604.1

**Comment by sibiraj-s** [comment]
For the given useragents.

ipad, except Opera and Firefox are not detected
ios - only opera is not detected.

These ones above that were not detected, they don't have enough information for parsing them, hence its not possible to detect them reliably.

**Comment by sibiraj-s** [comment]
May be i can parse for Opera it appears to be Opera Touch browser, I haven't seen that yet.

**Comment by sibiraj-s** [comment]
Thanks for opening the issue. Added support for Opera Touch in [v3.4.0.](https://www.npmjs.com/package/browser-dtector/v/3.4.0)

For FireFox on ipad. there is no way to detect that, hence no changes were made for that.
